apiVersion: v1
kind: LimitRange
metadata:
  name: hpclimits
  namespace: cluster-capacity
spec:
  limits:
  - max:
      cpu: "200m"
      memory: 100Mi
    min:
      cpu: 10m
      memory: 6Mi
    type: Pod
  - default:
      cpu: 10m
      memory: 6Mi
    defaultRequest:
      cpu: 10m
      memory: 6Mi
    max:
      cpu: "50m"
      memory: 20Mi
    min:
      cpu: 10m
      memory: 6Mi
    type: Container
